import { type } from "arktype";

/** Serializable canvas shapes. Layout and membership rules remain in the pure core. */
export const canvasModel = type.module({
  Number: "-9007199254740991 <= number <= 9007199254740991",
  PositiveNumber: "Number > 0",
  NonnegativeNumber: "Number >= 0",
  Count: "number.integer >= 1 & Number",
  Cell: "number.integer >= 0 & Number",
  Id: "string > 0",
  JsonPrimitive: "string | number | boolean | null",
  JsonObject: { "[string]": "JsonValue" },
  JsonValue: "JsonPrimitive | JsonObject | JsonValue[]",
  ComponentPropsEdit: {
    windowId: "Id",
    props: "JsonObject",
  },
  ComponentCreate: {
    "contentSize?": "Size",
    windowId: "Id",
    componentId: "Id",
    props: "JsonObject",
    "rect?": "Rect",
    "target?": "GroupInsertion",
  },
  Point: { x: "Number", y: "Number" },
  NormalizedPoint: { x: "0 <= number <= 1", y: "0 <= number <= 1" },
  Size: { height: "PositiveNumber", width: "PositiveNumber" },
  Rect: { "...": "Point", height: "PositiveNumber", width: "PositiveNumber" },
  Camera: { center: "Point", zoom: "PositiveNumber" },
  CameraFramingMode: "'horizontal' | 'vertical' | 'both'",
  CameraComposition: { "screenPosition?": "NormalizedPoint", "targetOffset?": "Point" },
  Direction: "'down' | 'left' | 'right' | 'up'",
  Alignment: "'bottom' | 'horizontal-center' | 'left' | 'right' | 'top' | 'vertical-center'",
  PlacementRegion:
    "'bottom' | 'bottom-left' | 'bottom-right' | 'center' | 'fill' | 'left' | 'right' | 'top' | 'top-left' | 'top-right'",
  CameraNavigationBehavior: [
    [{ type: "'center'" }, "|", { type: "'centerAtZoom'", zoom: "PositiveNumber" }],
    "|",
    {
      type: "'fit'",
      "maxZoom?": "PositiveNumber",
      "paddingPx?": "NonnegativeNumber",
      "framingMode?": "CameraFramingMode",
      "framingSize?": "PositiveNumber",
    },
  ],
  CameraNavigationTarget: [
    [
      [
        [{ type: "'point'", point: "Point" }, "|", { type: "'rect'", rect: "Rect" }],
        "|",
        { type: "'selection'" },
      ],
      "|",
      { type: "'visibleWindows'" },
    ],
    "|",
    [{ type: "'window'", windowId: "Id" }, "|", { type: "'group'", groupId: "Id" }],
  ],
  CameraNavigationRequest: {
    target: "CameraNavigationTarget",
    "behavior?": "CameraNavigationBehavior",
    "composition?": "CameraComposition",
  },
  WindowMode: "'normal' | 'minimized' | 'maximized'",
  WindowCapabilities: {
    "closable?": "boolean",
    "maximizable?": "boolean",
    "minimizable?": "boolean",
    "movable?": "boolean",
    "resizable?": "boolean",
  },
  Window: {
    "aspectRatio?": "PositiveNumber",
    "contentSize?": "Size",
    "heightMode?": "'content' | 'manual'",
    id: "string",
    kind: "string",
    title: "string",
    isPinned: "boolean",
    zIndex: "Number",
    minSize: "Size",
    rect: "Rect",
    "restoreRect?": "Rect",
    "data?": "unknown",
    mode: "WindowMode = 'normal'",
    "capabilities?": "WindowCapabilities",
  },
  SelectionTarget: [
    { id: "string", type: "'window'" },
    "|",
    {
      id: "string",
      kind: "string",
      type: "'edge' | 'group' | 'scene-object'",
      "data?": "unknown",
    },
  ],
  Selection: {
    anchorTarget: "SelectionTarget | null = null",
    targets: "SelectionTarget[]",
  },
  LengthPair: ["NonnegativeNumber", "NonnegativeNumber"],
  GroupAxis: "'horizontal' | 'vertical'",
  GroupLayoutMode: "'accordion' | 'masonry' | 'split' | 'tabs'",
  GroupMasonry: {
    "cols?": "Count",
    "maxRows?": "Count",
    "rowHeight?": "PositiveNumber",
    "margin?": "LengthPair",
    "containerPadding?": "LengthPair | null",
    "compactType?": "'horizontal' | 'vertical' | 'wrap' | null",
    "allowOverlap?": "boolean",
    "preventCollision?": "boolean",
    "responsive?": {
      "fitViewport?": "boolean",
      breakpoints: { "[string]": "NonnegativeNumber" },
      cols: { "[string]": "Count" },
    },
  },
  GroupWindowGridLayout: {
    "rows?": "Count",
    "span?": "Count",
    "x?": "Cell",
    "y?": "Cell",
  },
  GroupWindowLayout: {
    "...": "GroupWindowGridLayout",
    "hidden?": "boolean",
    "layouts?": { "[string]": "GroupWindowGridLayout" },
  },
  GroupInsertion: {
    groupId: "Id",
    "containerId?": "Id",
    "index?": "Cell",
    "layout?": "GroupWindowLayout",
  },
  GroupWindowNode: {
    "...": "GroupWindowLayout",
    id: "string",
    kind: "'window'",
    weight: "PositiveNumber",
  },
  GroupContainerHeader: {
    id: "string",
    kind: "'container'",
    weight: "PositiveNumber",
    activeChildId: "string | null",
    axis: "GroupAxis",
    layout: "GroupLayoutMode",
    children: "unknown[] > 0",
    "masonry?": "GroupMasonry",
  },
  GroupContainerNode: { "...": "GroupContainerHeader", children: "GroupNode[] > 0" },
  GroupNode: "GroupWindowNode | GroupContainerNode",
  GroupHeader: {
    id: "string",
    title: "string | null = null",
    rect: "Rect",
    zIndex: "Number",
    tree: "unknown",
    "bounds?": "'content' | Rect",
  },
  Group: { "...": "GroupHeader", tree: "GroupNode" },
  Workspace: {
    id: "string",
    title: "string",
    camera: "Camera",
    selection: "Selection",
    windowIds: "string[]",
  },
  Connection: { id: "string", kind: "string", from: "string", to: "string", "data?": "unknown" },
  RecipeWindow: {
    windowId: "string",
    isPinned: "boolean",
    mode: "WindowMode",
    rect: "Rect",
    zIndex: "Number",
  },
  RecipeGroupHeader: {
    groupId: "string",
    title: "string | null = null",
    rect: "Rect",
    zIndex: "Number",
    tree: "unknown",
    "bounds?": "'content' | Rect",
  },
  RecipeGroup: { "...": "RecipeGroupHeader", tree: "GroupNode" },
  RecipeEnvelope: {
    version: "1",
    id: "string",
    name: "string",
    size: "Size",
    windows: "unknown[]",
    groups: "unknown[]",
  },
  Recipe: { "...": "RecipeEnvelope", windows: "RecipeWindow[]", groups: "RecipeGroup[]" },
  SerializedState: {
    version: "4",
    activeWindowId: "string | null",
    camera: "Camera",
    windows: "Window[]",
    "selection?": "Selection",
    "groups?": "Group[]",
    "connections?": "Connection[]",
    "activeWorkspaceId?": "string | null",
    "workspaces?": "Workspace[]",
  },
});

const emptyCommandInput = type({});

export const commandInputs = {
  "selection.set": type({ selection: canvasModel.Selection }),
  "component.action": type({ actionId: canvasModel.Id, windowIds: canvasModel.Id.array() }),
  "desktop.reset": emptyCommandInput,
  "desktop.cancel": emptyCommandInput,
  "selection.clear": emptyCommandInput,
  "selection.group": type({
    "groupId?": canvasModel.Id,
    "layout?": canvasModel.GroupLayoutMode,
    "masonry?": canvasModel.GroupMasonry,
  }),
  "selection.selectAllVisible": emptyCommandInput,
  "view.fitAll": emptyCommandInput,
  "view.fitSelection": emptyCommandInput,
  "camera.navigate": type({ request: canvasModel.CameraNavigationRequest }),
  "window.nudge": type({ amountPx: canvasModel.Number, direction: canvasModel.Direction }),
  "window.align": type({ alignment: canvasModel.Alignment }),
  "group.equalizeChildren": type({ "groupId?": canvasModel.Id, "containerId?": canvasModel.Id }),
  "activeWindow.close": emptyCommandInput,
  "activeWindow.minimize": emptyCommandInput,
  "activeWindow.toggleMaximized": emptyCommandInput,
  "activeWindow.togglePinned": emptyCommandInput,
  "selection.close": emptyCommandInput,
  "selection.minimize": emptyCommandInput,
  "selection.togglePinned": emptyCommandInput,
  "view.pan": type({ amountPx: canvasModel.Number, direction: canvasModel.Direction }),
  "view.zoomBy": type({ factor: canvasModel.PositiveNumber }),
  "selection.extendDirection": type({ direction: canvasModel.Direction }),
  "selection.removeActive": emptyCommandInput,
  "workspace.cycle": type({ direction: "'next' | 'previous'" }),
  "workspace.showAll": emptyCommandInput,
  "workspace.removeActiveWindow": emptyCommandInput,
  "workspace.create": type({
    "activate?": "boolean",
    "title?": "string",
    "windowIds?": "string[]",
    workspaceId: canvasModel.Id,
  }),
  "workspace.enter": type({ workspaceId: canvasModel.Id }),
  "workspace.close": type({ workspaceId: canvasModel.Id }),
  "workspace.moveActiveWindow": type({ workspaceId: canvasModel.Id }),
  "window.reveal": type({ windowId: canvasModel.Id }),
  "window.close": type({ windowId: canvasModel.Id }),
  "window.minimize": type({ windowId: canvasModel.Id }),
  "window.maximize": type({ windowId: canvasModel.Id }),
  "window.restore": type({ windowId: canvasModel.Id }),
  "group.resizePane": type({ amountPx: canvasModel.Number }),
  "group.dissolve": emptyCommandInput,
  "group.fitContents": type({ "groupId?": canvasModel.Id }),
  "group.setBounds": type({ groupId: canvasModel.Id, bounds: canvasModel.Rect.or("'content'") }),
  "group.flipAxis": emptyCommandInput,
  "group.moveChild": type({ toward: "'end' | 'start'" }),
  "group.setLayout": type({ layout: canvasModel.GroupLayoutMode }),
  "window.dockDirection": type({ direction: canvasModel.Direction }),
  "window.undock": emptyCommandInput,
  "window.swap": emptyCommandInput,
  "window.pack": type({ "gapPx?": canvasModel.Number }),
  "window.distribute": type({ distribution: canvasModel.GroupAxis }),
  "window.place": type({ region: canvasModel.PlacementRegion }),
  "window.resize": type({ amountPx: canvasModel.Number, direction: canvasModel.Direction }),
  "window.focusDirection": type({ direction: canvasModel.Direction }),
  "history.undo": emptyCommandInput,
  "history.redo": emptyCommandInput,
  "view.resetZoom": emptyCommandInput,
};
