import { type } from "arktype";

/** Serializable canvas shapes. Layout and membership rules remain in the pure core. */
export const canvasModel = type.module({
  Number: "-9007199254740991 <= number <= 9007199254740991",
  PositiveNumber: "Number > 0",
  NonnegativeNumber: "Number >= 0",
  Count: "number.integer >= 1 & Number",
  Cell: "number.integer >= 0 & Number",
  Id: "string > 0",
  JsonPrimitive: "string | number | boolean | null",
  JsonObject: { "[string]": "JsonValue" },
  JsonValue: "JsonPrimitive | JsonObject | JsonValue[]",
  DefinitionRef: { id: "Id", contractVersion: "number.integer > 0" },
  RecordRef: { recordId: "Id", model: "DefinitionRef" },
  LiteralValue: { kind: "'literal'", value: "JsonValue" },
  RecordBinding: {
    kind: "'binding'",
    source: { kind: "'record'", record: "RecordRef" },
    path: "(string | number.integer >= 0)[]",
    "fallback?": "JsonValue",
  },
  PropertyValue: "LiteralValue | RecordBinding",
  ComponentNode: {
    revision: "number.integer >= 0 = 0",
    id: "Id", kind: "'component'", component: "DefinitionRef",
    props: { "[string]": "PropertyValue" },
    slots: { "[string]": "Id[]" },
  },
  ComponentPropsEdit: {
    windowId: "Id", expectedRevision: "number.integer >= 0", props: "JsonObject",
    "bindings?": { "[string]": "RecordBinding" }, "reset?": "Id[]",
  },
  ComponentCreate: { windowId: "Id", componentId: "Id", props: "JsonObject", "rect?": "Rect", "target?": "GroupInsertion" },
  Point: { x: "Number", y: "Number" },
  Size: { height: "PositiveNumber", width: "PositiveNumber" },
  Rect: { "...": "Point", height: "PositiveNumber", width: "PositiveNumber" },
  Camera: { center: "Point", zoom: "PositiveNumber" },
  WindowMode: "'normal' | 'minimized' | 'maximized'",
  WindowCapabilities: {
    "closable?": "boolean", "maximizable?": "boolean", "minimizable?": "boolean",
    "movable?": "boolean", "resizable?": "boolean",
  },
  Window: {
    "heightMode?": "'content' | 'manual'",
    id: "string", kind: "string", title: "string", isPinned: "boolean", zIndex: "Number",
    minSize: "Size", rect: "Rect", "restoreRect?": "Rect", "data?": "unknown",
    mode: "WindowMode = 'normal'", "capabilities?": "WindowCapabilities",
  },
  SelectionTarget: { id: "string", kind: "string", type: "'edge' | 'scene-object'", "data?": "unknown" },
  Selection: {
    anchorWindowId: "string | null = null", windowIds: "string[]",
    "anchorTarget?": "SelectionTarget | null", "targets?": "SelectionTarget[]",
  },
  LengthPair: ["NonnegativeNumber", "NonnegativeNumber"],
  GroupAxis: "'horizontal' | 'vertical'",
  GroupLayoutMode: "'accordion' | 'masonry' | 'split' | 'tabs'",
  GroupMasonry: {
    "cols?": "Count", "maxRows?": "Count", "rowHeight?": "PositiveNumber",
    "margin?": "LengthPair", "containerPadding?": "LengthPair | null",
    "compactType?": "'horizontal' | 'vertical' | 'wrap' | null",
    "allowOverlap?": "boolean", "preventCollision?": "boolean",
  },
  GroupWindowLayout: {
    "rows?": "Count", "span?": "Count", "x?": "Cell", "y?": "Cell", "hidden?": "boolean",
  },
  GroupInsertion: { groupId: "Id", "containerId?": "Id", "index?": "Cell", "layout?": "GroupWindowLayout" },
  GroupWindowNode: { "...": "GroupWindowLayout", id: "string", kind: "'window'", weight: "PositiveNumber" },
  GroupContainerHeader: {
    id: "string", kind: "'container'", weight: "PositiveNumber",
    activeChildId: "string | null", axis: "GroupAxis", layout: "GroupLayoutMode",
    children: "unknown[] > 0", "masonry?": "GroupMasonry",
  },
  GroupContainerNode: { "...": "GroupContainerHeader", children: "GroupNode[] > 0" },
  GroupNode: "GroupWindowNode | GroupContainerNode",
  GroupHeader: { id: "string", title: "string | null = null", rect: "Rect", zIndex: "Number", tree: "unknown" },
  Group: { "...": "GroupHeader", tree: "GroupNode" },
  Workspace: { id: "string", title: "string", camera: "Camera", selection: "Selection", windowIds: "string[]" },
  Connection: { id: "string", kind: "string", from: "string", to: "string", "data?": "unknown" },
  RecipeWindow: { windowId: "string", isPinned: "boolean", mode: "WindowMode", rect: "Rect", zIndex: "Number" },
  RecipeGroupHeader: { groupId: "string", title: "string | null = null", rect: "Rect", zIndex: "Number", tree: "unknown" },
  RecipeGroup: { "...": "RecipeGroupHeader", tree: "GroupNode" },
  RecipeEnvelope: { version: "1", id: "string", name: "string", size: "Size", windows: "unknown[]", groups: "unknown[]" },
  Recipe: { "...": "RecipeEnvelope", windows: "RecipeWindow[]", groups: "RecipeGroup[]" },
  PersistenceEnvelope: {
    version: "1 | 2 | 3 | 4", activeWindowId: "string | null", camera: "Camera",
    windows: "unknown[]", "selection?": "Selection", "groups?": "unknown[]",
    "connections?": "Connection[]", "activeWorkspaceId?": "string | null", "workspaces?": "Workspace[]",
  },
  SerializedState: {
    "...": "PersistenceEnvelope", version: "4", windows: "Window[]", "groups?": "Group[]",
  },
});
