import {
  ArrowDownToLineIcon,
  ArrowUpFromLineIcon,
  BookmarkIcon,
  CircleSlashIcon,
  CopyPlusIcon,
  CornerUpLeftIcon,
  CornerUpRightIcon,
  CrosshairIcon,
  GroupIcon,
  LayoutGridIcon,
  LayersIcon,
  MaximizeIcon,
  MinimizeIcon,
  MousePointerSquareDashedIcon,
  MoveIcon,
  PencilIcon,
  PinIcon,
  PlusIcon,
  RotateCcwIcon,
  ScalingIcon,
  SquareArrowOutUpRightIcon,
  Trash2Icon,
  TypeIcon,
  UngroupIcon,
  XIcon,
  type LucideIcon,
} from "lucide-react";

/** The command registry names an icon; the glyph is the consumer's choice. */
export const canvasIcons: Readonly<Record<string, LucideIcon>> = {
  add: PlusIcon,
  close: XIcon,
  dock: ArrowDownToLineIcon,
  edit: PencilIcon,
  fit: CrosshairIcon,
  focus: MousePointerSquareDashedIcon,
  group: GroupIcon,
  layout: LayoutGridIcon,
  maximize: MaximizeIcon,
  minimize: MinimizeIcon,
  move: MoveIcon,
  pin: PinIcon,
  redo: CornerUpRightIcon,
  remove: Trash2Icon,
  rename: TypeIcon,
  reorder: LayersIcon,
  reset: RotateCcwIcon,
  resize: ScalingIcon,
  restore: SquareArrowOutUpRightIcon,
  section: BookmarkIcon,
  select: CopyPlusIcon,
  stop: CircleSlashIcon,
  undo: CornerUpLeftIcon,
  undock: ArrowUpFromLineIcon,
  ungroup: UngroupIcon,
  workspace: LayersIcon,
};
