/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WidgetsRouteImport } from './routes/widgets'
import { Route as ReadoutsRouteImport } from './routes/readouts'
import { Route as OverlaysRouteImport } from './routes/overlays'
import { Route as LayoutRouteImport } from './routes/layout'
import { Route as FoundationsRouteImport } from './routes/foundations'
import { Route as DisclosureRouteImport } from './routes/disclosure'
import { Route as ControlsRouteImport } from './routes/controls'
import { Route as IndexRouteImport } from './routes/index'

const WidgetsRoute = WidgetsRouteImport.update({
  id: '/widgets',
  path: '/widgets',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadoutsRoute = ReadoutsRouteImport.update({
  id: '/readouts',
  path: '/readouts',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlaysRoute = OverlaysRouteImport.update({
  id: '/overlays',
  path: '/overlays',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/layout',
  path: '/layout',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundationsRoute = FoundationsRouteImport.update({
  id: '/foundations',
  path: '/foundations',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclosureRoute = DisclosureRouteImport.update({
  id: '/disclosure',
  path: '/disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlsRoute = ControlsRouteImport.update({
  id: '/controls',
  path: '/controls',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/controls': typeof ControlsRoute
  '/disclosure': typeof DisclosureRoute
  '/foundations': typeof FoundationsRoute
  '/layout': typeof LayoutRoute
  '/overlays': typeof OverlaysRoute
  '/readouts': typeof ReadoutsRoute
  '/widgets': typeof WidgetsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/controls': typeof ControlsRoute
  '/disclosure': typeof DisclosureRoute
  '/foundations': typeof FoundationsRoute
  '/layout': typeof LayoutRoute
  '/overlays': typeof OverlaysRoute
  '/readouts': typeof ReadoutsRoute
  '/widgets': typeof WidgetsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/controls': typeof ControlsRoute
  '/disclosure': typeof DisclosureRoute
  '/foundations': typeof FoundationsRoute
  '/layout': typeof LayoutRoute
  '/overlays': typeof OverlaysRoute
  '/readouts': typeof ReadoutsRoute
  '/widgets': typeof WidgetsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/controls'
    | '/disclosure'
    | '/foundations'
    | '/layout'
    | '/overlays'
    | '/readouts'
    | '/widgets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/controls'
    | '/disclosure'
    | '/foundations'
    | '/layout'
    | '/overlays'
    | '/readouts'
    | '/widgets'
  id:
    | '__root__'
    | '/'
    | '/controls'
    | '/disclosure'
    | '/foundations'
    | '/layout'
    | '/overlays'
    | '/readouts'
    | '/widgets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ControlsRoute: typeof ControlsRoute
  DisclosureRoute: typeof DisclosureRoute
  FoundationsRoute: typeof FoundationsRoute
  LayoutRoute: typeof LayoutRoute
  OverlaysRoute: typeof OverlaysRoute
  ReadoutsRoute: typeof ReadoutsRoute
  WidgetsRoute: typeof WidgetsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/widgets': {
      id: '/widgets'
      path: '/widgets'
      fullPath: '/widgets'
      preLoaderRoute: typeof WidgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readouts': {
      id: '/readouts'
      path: '/readouts'
      fullPath: '/readouts'
      preLoaderRoute: typeof ReadoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlays': {
      id: '/overlays'
      path: '/overlays'
      fullPath: '/overlays'
      preLoaderRoute: typeof OverlaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layout': {
      id: '/layout'
      path: '/layout'
      fullPath: '/layout'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundations': {
      id: '/foundations'
      path: '/foundations'
      fullPath: '/foundations'
      preLoaderRoute: typeof FoundationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclosure': {
      id: '/disclosure'
      path: '/disclosure'
      fullPath: '/disclosure'
      preLoaderRoute: typeof DisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controls': {
      id: '/controls'
      path: '/controls'
      fullPath: '/controls'
      preLoaderRoute: typeof ControlsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ControlsRoute: ControlsRoute,
  DisclosureRoute: DisclosureRoute,
  FoundationsRoute: FoundationsRoute,
  LayoutRoute: LayoutRoute,
  OverlaysRoute: OverlaysRoute,
  ReadoutsRoute: ReadoutsRoute,
  WidgetsRoute: WidgetsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
