/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ControlsRouteImport } from './routes/controls'
import { Route as DisclosureRouteImport } from './routes/disclosure'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as FormsRouteImport } from './routes/forms'
import { Route as FoundationsRouteImport } from './routes/foundations'
import { Route as LayoutRouteImport } from './routes/layout'
import { Route as OverlaysRouteImport } from './routes/overlays'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as ReadoutsRouteImport } from './routes/readouts'
import { Route as TylerRouteImport } from './routes/tyler'
import { Route as WidgetsRouteImport } from './routes/widgets'
import { Route as AuthPathRouteImport } from './routes/auth.$path'
import { Route as PIdRouteImport } from './routes/p.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ControlsRoute = ControlsRouteImport.update({
  id: '/controls',
  path: '/controls',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclosureRoute = DisclosureRouteImport.update({
  id: '/disclosure',
  path: '/disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsRoute = FormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundationsRoute = FoundationsRouteImport.update({
  id: '/foundations',
  path: '/foundations',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/layout',
  path: '/layout',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlaysRoute = OverlaysRouteImport.update({
  id: '/overlays',
  path: '/overlays',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadoutsRoute = ReadoutsRouteImport.update({
  id: '/readouts',
  path: '/readouts',
  getParentRoute: () => rootRouteImport,
} as any)
const TylerRoute = TylerRouteImport.update({
  id: '/tyler',
  path: '/tyler',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetsRoute = WidgetsRouteImport.update({
  id: '/widgets',
  path: '/widgets',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPathRoute = AuthPathRouteImport.update({
  id: '/auth/$path',
  path: '/auth/$path',
  getParentRoute: () => rootRouteImport,
} as any)
const PIdRoute = PIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/controls': typeof ControlsRoute
  '/disclosure': typeof DisclosureRoute
  '/editor': typeof EditorRoute
  '/forms': typeof FormsRoute
  '/foundations': typeof FoundationsRoute
  '/layout': typeof LayoutRoute
  '/overlays': typeof OverlaysRoute
  '/overview': typeof OverviewRoute
  '/readouts': typeof ReadoutsRoute
  '/tyler': typeof TylerRoute
  '/widgets': typeof WidgetsRoute
  '/auth/$path': typeof AuthPathRoute
  '/p/$id': typeof PIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/controls': typeof ControlsRoute
  '/disclosure': typeof DisclosureRoute
  '/editor': typeof EditorRoute
  '/forms': typeof FormsRoute
  '/foundations': typeof FoundationsRoute
  '/layout': typeof LayoutRoute
  '/overlays': typeof OverlaysRoute
  '/overview': typeof OverviewRoute
  '/readouts': typeof ReadoutsRoute
  '/tyler': typeof TylerRoute
  '/widgets': typeof WidgetsRoute
  '/auth/$path': typeof AuthPathRoute
  '/p/$id': typeof PIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/controls': typeof ControlsRoute
  '/disclosure': typeof DisclosureRoute
  '/editor': typeof EditorRoute
  '/forms': typeof FormsRoute
  '/foundations': typeof FoundationsRoute
  '/layout': typeof LayoutRoute
  '/overlays': typeof OverlaysRoute
  '/overview': typeof OverviewRoute
  '/readouts': typeof ReadoutsRoute
  '/tyler': typeof TylerRoute
  '/widgets': typeof WidgetsRoute
  '/auth/$path': typeof AuthPathRoute
  '/p/$id': typeof PIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/controls'
    | '/disclosure'
    | '/editor'
    | '/forms'
    | '/foundations'
    | '/layout'
    | '/overlays'
    | '/overview'
    | '/readouts'
    | '/tyler'
    | '/widgets'
    | '/auth/$path'
    | '/p/$id'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/controls'
    | '/disclosure'
    | '/editor'
    | '/forms'
    | '/foundations'
    | '/layout'
    | '/overlays'
    | '/overview'
    | '/readouts'
    | '/tyler'
    | '/widgets'
    | '/auth/$path'
    | '/p/$id'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/controls'
    | '/disclosure'
    | '/editor'
    | '/forms'
    | '/foundations'
    | '/layout'
    | '/overlays'
    | '/overview'
    | '/readouts'
    | '/tyler'
    | '/widgets'
    | '/auth/$path'
    | '/p/$id'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ControlsRoute: typeof ControlsRoute
  DisclosureRoute: typeof DisclosureRoute
  EditorRoute: typeof EditorRoute
  FormsRoute: typeof FormsRoute
  FoundationsRoute: typeof FoundationsRoute
  LayoutRoute: typeof LayoutRoute
  OverlaysRoute: typeof OverlaysRoute
  OverviewRoute: typeof OverviewRoute
  ReadoutsRoute: typeof ReadoutsRoute
  TylerRoute: typeof TylerRoute
  WidgetsRoute: typeof WidgetsRoute
  AuthPathRoute: typeof AuthPathRoute
  PIdRoute: typeof PIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/controls': {
      id: '/controls'
      path: '/controls'
      fullPath: '/controls'
      preLoaderRoute: typeof ControlsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclosure': {
      id: '/disclosure'
      path: '/disclosure'
      fullPath: '/disclosure'
      preLoaderRoute: typeof DisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms': {
      id: '/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof FormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/foundations': {
      id: '/foundations'
      path: '/foundations'
      fullPath: '/foundations'
      preLoaderRoute: typeof FoundationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layout': {
      id: '/layout'
      path: '/layout'
      fullPath: '/layout'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlays': {
      id: '/overlays'
      path: '/overlays'
      fullPath: '/overlays'
      preLoaderRoute: typeof OverlaysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readouts': {
      id: '/readouts'
      path: '/readouts'
      fullPath: '/readouts'
      preLoaderRoute: typeof ReadoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tyler': {
      id: '/tyler'
      path: '/tyler'
      fullPath: '/tyler'
      preLoaderRoute: typeof TylerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widgets': {
      id: '/widgets'
      path: '/widgets'
      fullPath: '/widgets'
      preLoaderRoute: typeof WidgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$path': {
      id: '/auth/$path'
      path: '/auth/$path'
      fullPath: '/auth/$path'
      preLoaderRoute: typeof AuthPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$id': {
      id: '/p/$id'
      path: '/p/$id'
      fullPath: '/p/$id'
      preLoaderRoute: typeof PIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ControlsRoute: ControlsRoute,
  DisclosureRoute: DisclosureRoute,
  EditorRoute: EditorRoute,
  FormsRoute: FormsRoute,
  FoundationsRoute: FoundationsRoute,
  LayoutRoute: LayoutRoute,
  OverlaysRoute: OverlaysRoute,
  OverviewRoute: OverviewRoute,
  ReadoutsRoute: ReadoutsRoute,
  TylerRoute: TylerRoute,
  WidgetsRoute: WidgetsRoute,
  AuthPathRoute: AuthPathRoute,
  PIdRoute: PIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
