/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspacesRouteImport } from './routes/workspaces'
import { Route as WorkflowBoardRouteImport } from './routes/workflow-board'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as StressRouteImport } from './routes/stress'
import { Route as StageTemplateRouteImport } from './routes/stage-template'
import { Route as PortalsRouteImport } from './routes/portals'
import { Route as PersistenceRouteImport } from './routes/persistence'
import { Route as NormalRouteImport } from './routes/normal'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as DropTrayRouteImport } from './routes/drop-tray'
import { Route as CustomFramesRouteImport } from './routes/custom-frames'
import { Route as BodyContentRouteImport } from './routes/body-content'
import { Route as IndexRouteImport } from './routes/index'

const WorkspacesRoute = WorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowBoardRoute = WorkflowBoardRouteImport.update({
  id: '/workflow-board',
  path: '/workflow-board',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const StressRoute = StressRouteImport.update({
  id: '/stress',
  path: '/stress',
  getParentRoute: () => rootRouteImport,
} as any)
const StageTemplateRoute = StageTemplateRouteImport.update({
  id: '/stage-template',
  path: '/stage-template',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalsRoute = PortalsRouteImport.update({
  id: '/portals',
  path: '/portals',
  getParentRoute: () => rootRouteImport,
} as any)
const PersistenceRoute = PersistenceRouteImport.update({
  id: '/persistence',
  path: '/persistence',
  getParentRoute: () => rootRouteImport,
} as any)
const NormalRoute = NormalRouteImport.update({
  id: '/normal',
  path: '/normal',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const DropTrayRoute = DropTrayRouteImport.update({
  id: '/drop-tray',
  path: '/drop-tray',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomFramesRoute = CustomFramesRouteImport.update({
  id: '/custom-frames',
  path: '/custom-frames',
  getParentRoute: () => rootRouteImport,
} as any)
const BodyContentRoute = BodyContentRouteImport.update({
  id: '/body-content',
  path: '/body-content',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/body-content': typeof BodyContentRoute
  '/custom-frames': typeof CustomFramesRoute
  '/drop-tray': typeof DropTrayRoute
  '/groups': typeof GroupsRoute
  '/normal': typeof NormalRoute
  '/persistence': typeof PersistenceRoute
  '/portals': typeof PortalsRoute
  '/stage-template': typeof StageTemplateRoute
  '/stress': typeof StressRoute
  '/welcome': typeof WelcomeRoute
  '/workflow-board': typeof WorkflowBoardRoute
  '/workspaces': typeof WorkspacesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/body-content': typeof BodyContentRoute
  '/custom-frames': typeof CustomFramesRoute
  '/drop-tray': typeof DropTrayRoute
  '/groups': typeof GroupsRoute
  '/normal': typeof NormalRoute
  '/persistence': typeof PersistenceRoute
  '/portals': typeof PortalsRoute
  '/stage-template': typeof StageTemplateRoute
  '/stress': typeof StressRoute
  '/welcome': typeof WelcomeRoute
  '/workflow-board': typeof WorkflowBoardRoute
  '/workspaces': typeof WorkspacesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/body-content': typeof BodyContentRoute
  '/custom-frames': typeof CustomFramesRoute
  '/drop-tray': typeof DropTrayRoute
  '/groups': typeof GroupsRoute
  '/normal': typeof NormalRoute
  '/persistence': typeof PersistenceRoute
  '/portals': typeof PortalsRoute
  '/stage-template': typeof StageTemplateRoute
  '/stress': typeof StressRoute
  '/welcome': typeof WelcomeRoute
  '/workflow-board': typeof WorkflowBoardRoute
  '/workspaces': typeof WorkspacesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/body-content'
    | '/custom-frames'
    | '/drop-tray'
    | '/groups'
    | '/normal'
    | '/persistence'
    | '/portals'
    | '/stage-template'
    | '/stress'
    | '/welcome'
    | '/workflow-board'
    | '/workspaces'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/body-content'
    | '/custom-frames'
    | '/drop-tray'
    | '/groups'
    | '/normal'
    | '/persistence'
    | '/portals'
    | '/stage-template'
    | '/stress'
    | '/welcome'
    | '/workflow-board'
    | '/workspaces'
  id:
    | '__root__'
    | '/'
    | '/body-content'
    | '/custom-frames'
    | '/drop-tray'
    | '/groups'
    | '/normal'
    | '/persistence'
    | '/portals'
    | '/stage-template'
    | '/stress'
    | '/welcome'
    | '/workflow-board'
    | '/workspaces'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BodyContentRoute: typeof BodyContentRoute
  CustomFramesRoute: typeof CustomFramesRoute
  DropTrayRoute: typeof DropTrayRoute
  GroupsRoute: typeof GroupsRoute
  NormalRoute: typeof NormalRoute
  PersistenceRoute: typeof PersistenceRoute
  PortalsRoute: typeof PortalsRoute
  StageTemplateRoute: typeof StageTemplateRoute
  StressRoute: typeof StressRoute
  WelcomeRoute: typeof WelcomeRoute
  WorkflowBoardRoute: typeof WorkflowBoardRoute
  WorkspacesRoute: typeof WorkspacesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspaces': {
      id: '/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof WorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow-board': {
      id: '/workflow-board'
      path: '/workflow-board'
      fullPath: '/workflow-board'
      preLoaderRoute: typeof WorkflowBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stress': {
      id: '/stress'
      path: '/stress'
      fullPath: '/stress'
      preLoaderRoute: typeof StressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stage-template': {
      id: '/stage-template'
      path: '/stage-template'
      fullPath: '/stage-template'
      preLoaderRoute: typeof StageTemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portals': {
      id: '/portals'
      path: '/portals'
      fullPath: '/portals'
      preLoaderRoute: typeof PortalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persistence': {
      id: '/persistence'
      path: '/persistence'
      fullPath: '/persistence'
      preLoaderRoute: typeof PersistenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/normal': {
      id: '/normal'
      path: '/normal'
      fullPath: '/normal'
      preLoaderRoute: typeof NormalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drop-tray': {
      id: '/drop-tray'
      path: '/drop-tray'
      fullPath: '/drop-tray'
      preLoaderRoute: typeof DropTrayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-frames': {
      id: '/custom-frames'
      path: '/custom-frames'
      fullPath: '/custom-frames'
      preLoaderRoute: typeof CustomFramesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/body-content': {
      id: '/body-content'
      path: '/body-content'
      fullPath: '/body-content'
      preLoaderRoute: typeof BodyContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BodyContentRoute: BodyContentRoute,
  CustomFramesRoute: CustomFramesRoute,
  DropTrayRoute: DropTrayRoute,
  GroupsRoute: GroupsRoute,
  NormalRoute: NormalRoute,
  PersistenceRoute: PersistenceRoute,
  PortalsRoute: PortalsRoute,
  StageTemplateRoute: StageTemplateRoute,
  StressRoute: StressRoute,
  WelcomeRoute: WelcomeRoute,
  WorkflowBoardRoute: WorkflowBoardRoute,
  WorkspacesRoute: WorkspacesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
