/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as StageTemplateRouteImport } from './routes/stage-template'
import { Route as NormalRouteImport } from './routes/normal'
import { Route as DynamicGridRouteImport } from './routes/dynamic-grid'
import { Route as IndexRouteImport } from './routes/index'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const StageTemplateRoute = StageTemplateRouteImport.update({
  id: '/stage-template',
  path: '/stage-template',
  getParentRoute: () => rootRouteImport,
} as any)
const NormalRoute = NormalRouteImport.update({
  id: '/normal',
  path: '/normal',
  getParentRoute: () => rootRouteImport,
} as any)
const DynamicGridRoute = DynamicGridRouteImport.update({
  id: '/dynamic-grid',
  path: '/dynamic-grid',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dynamic-grid': typeof DynamicGridRoute
  '/normal': typeof NormalRoute
  '/stage-template': typeof StageTemplateRoute
  '/welcome': typeof WelcomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dynamic-grid': typeof DynamicGridRoute
  '/normal': typeof NormalRoute
  '/stage-template': typeof StageTemplateRoute
  '/welcome': typeof WelcomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dynamic-grid': typeof DynamicGridRoute
  '/normal': typeof NormalRoute
  '/stage-template': typeof StageTemplateRoute
  '/welcome': typeof WelcomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dynamic-grid' | '/normal' | '/stage-template' | '/welcome'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dynamic-grid' | '/normal' | '/stage-template' | '/welcome'
  id:
    | '__root__'
    | '/'
    | '/dynamic-grid'
    | '/normal'
    | '/stage-template'
    | '/welcome'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DynamicGridRoute: typeof DynamicGridRoute
  NormalRoute: typeof NormalRoute
  StageTemplateRoute: typeof StageTemplateRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stage-template': {
      id: '/stage-template'
      path: '/stage-template'
      fullPath: '/stage-template'
      preLoaderRoute: typeof StageTemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/normal': {
      id: '/normal'
      path: '/normal'
      fullPath: '/normal'
      preLoaderRoute: typeof NormalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dynamic-grid': {
      id: '/dynamic-grid'
      path: '/dynamic-grid'
      fullPath: '/dynamic-grid'
      preLoaderRoute: typeof DynamicGridRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DynamicGridRoute: DynamicGridRoute,
  NormalRoute: NormalRoute,
  StageTemplateRoute: StageTemplateRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
