/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkflowBoardRouteImport } from './routes/workflow-board'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as StressRouteImport } from './routes/stress'
import { Route as StageTemplateRouteImport } from './routes/stage-template'
import { Route as PersistenceRouteImport } from './routes/persistence'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as NormalRouteImport } from './routes/normal'
import { Route as DropTrayRouteImport } from './routes/drop-tray'
import { Route as CustomFramesRouteImport } from './routes/custom-frames'
import { Route as IndexRouteImport } from './routes/index'

const WorkflowBoardRoute = WorkflowBoardRouteImport.update({
  id: '/workflow-board',
  path: '/workflow-board',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const StressRoute = StressRouteImport.update({
  id: '/stress',
  path: '/stress',
  getParentRoute: () => rootRouteImport,
} as any)
const StageTemplateRoute = StageTemplateRouteImport.update({
  id: '/stage-template',
  path: '/stage-template',
  getParentRoute: () => rootRouteImport,
} as any)
const PersistenceRoute = PersistenceRouteImport.update({
  id: '/persistence',
  path: '/persistence',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const NormalRoute = NormalRouteImport.update({
  id: '/normal',
  path: '/normal',
  getParentRoute: () => rootRouteImport,
} as any)
const DropTrayRoute = DropTrayRouteImport.update({
  id: '/drop-tray',
  path: '/drop-tray',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomFramesRoute = CustomFramesRouteImport.update({
  id: '/custom-frames',
  path: '/custom-frames',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/custom-frames': typeof CustomFramesRoute
  '/drop-tray': typeof DropTrayRoute
  '/normal': typeof NormalRoute
  '/groups': typeof GroupsRoute
  '/persistence': typeof PersistenceRoute
  '/stage-template': typeof StageTemplateRoute
  '/stress': typeof StressRoute
  '/welcome': typeof WelcomeRoute
  '/workflow-board': typeof WorkflowBoardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/custom-frames': typeof CustomFramesRoute
  '/drop-tray': typeof DropTrayRoute
  '/normal': typeof NormalRoute
  '/groups': typeof GroupsRoute
  '/persistence': typeof PersistenceRoute
  '/stage-template': typeof StageTemplateRoute
  '/stress': typeof StressRoute
  '/welcome': typeof WelcomeRoute
  '/workflow-board': typeof WorkflowBoardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/custom-frames': typeof CustomFramesRoute
  '/drop-tray': typeof DropTrayRoute
  '/normal': typeof NormalRoute
  '/groups': typeof GroupsRoute
  '/persistence': typeof PersistenceRoute
  '/stage-template': typeof StageTemplateRoute
  '/stress': typeof StressRoute
  '/welcome': typeof WelcomeRoute
  '/workflow-board': typeof WorkflowBoardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/custom-frames'
    | '/drop-tray'
    | '/normal'
    | '/groups'
    | '/persistence'
    | '/stage-template'
    | '/stress'
    | '/welcome'
    | '/workflow-board'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/custom-frames'
    | '/drop-tray'
    | '/normal'
    | '/groups'
    | '/persistence'
    | '/stage-template'
    | '/stress'
    | '/welcome'
    | '/workflow-board'
  id:
    | '__root__'
    | '/'
    | '/custom-frames'
    | '/drop-tray'
    | '/normal'
    | '/groups'
    | '/persistence'
    | '/stage-template'
    | '/stress'
    | '/welcome'
    | '/workflow-board'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomFramesRoute: typeof CustomFramesRoute
  DropTrayRoute: typeof DropTrayRoute
  NormalRoute: typeof NormalRoute
  GroupsRoute: typeof GroupsRoute
  PersistenceRoute: typeof PersistenceRoute
  StageTemplateRoute: typeof StageTemplateRoute
  StressRoute: typeof StressRoute
  WelcomeRoute: typeof WelcomeRoute
  WorkflowBoardRoute: typeof WorkflowBoardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workflow-board': {
      id: '/workflow-board'
      path: '/workflow-board'
      fullPath: '/workflow-board'
      preLoaderRoute: typeof WorkflowBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stress': {
      id: '/stress'
      path: '/stress'
      fullPath: '/stress'
      preLoaderRoute: typeof StressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stage-template': {
      id: '/stage-template'
      path: '/stage-template'
      fullPath: '/stage-template'
      preLoaderRoute: typeof StageTemplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persistence': {
      id: '/persistence'
      path: '/persistence'
      fullPath: '/persistence'
      preLoaderRoute: typeof PersistenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/normal': {
      id: '/normal'
      path: '/normal'
      fullPath: '/normal'
      preLoaderRoute: typeof NormalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drop-tray': {
      id: '/drop-tray'
      path: '/drop-tray'
      fullPath: '/drop-tray'
      preLoaderRoute: typeof DropTrayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-frames': {
      id: '/custom-frames'
      path: '/custom-frames'
      fullPath: '/custom-frames'
      preLoaderRoute: typeof CustomFramesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomFramesRoute: CustomFramesRoute,
  DropTrayRoute: DropTrayRoute,
  NormalRoute: NormalRoute,
  GroupsRoute: GroupsRoute,
  PersistenceRoute: PersistenceRoute,
  StageTemplateRoute: StageTemplateRoute,
  StressRoute: StressRoute,
  WelcomeRoute: WelcomeRoute,
  WorkflowBoardRoute: WorkflowBoardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
